spring:
  application:
    name: service-auth
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
    password: avicit
    database: 0
mybatis:
  mapper-locations: classpath:mapper/*.xml
